name: CI Pipeline

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test-sum
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'
      
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test
      
